### ISSUE TITLE
Add Acknowledgement and Citation of MST

### ISSUE THREAD

**Issue by caiyuanhao1998** [Krito-ex/CSST#1]
Hi,

I noticed that this repo is heavily borrowed from our [MST](https://github.com/caiyuanhao1998/MST) repo, even the `my_summary` function.

However, I have not seen the acknowledgment to clarify this or citations about our works in this repo.

This is not professional

**Comment by caiyuanhao1998** [comment]
You didn't even give our repo a star

**Comment by caiyuanhao1998** [comment]
The same as [MST_plus_plus](https://github.com/caiyuanhao1998/MST-plus-plus) repo

**Comment by Krito-ex** [comment]
I'm glad you noticed it and gave me valuable advice, the initial open source was relatively hasty and many omissions we will fix immediately～



---- Replied Message ----
| From | Yuanhao ***@***.***> |
| Date | 10/27/2023 10:24 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Krito-ex/CSST] Add Acknowledgement and Citation of MST (Issue #1) |

Hi,

I noticed that this repo is heavily borrowed from our MST repo, even the my_summary function.

However, I have not seen the acknowledgment to clarify this or citations about our works in this repo.

This is not professional

**Comment by caiyuanhao1998** [comment]
Good, thank you
